### ISSUE TITLE
Installation instructions need update

### ISSUE THREAD

**Issue by straight-shoota** [crystal-jp/ja.crystal-lang.org#126]
See https://crystal-lang.org/2021/04/30/new-apt-and-rpm-repositories.html

/cc https://github.com/crystal-lang/crystal-website/pull/138

**Comment by makenowjust** [comment]
@straight-shoota Okay. I will fix it tomorrow.

**Comment by makenowjust** [comment]
Done in #127 and commits after it.

Blog posts are not translated, but installation instructions are updated. I wish it helps Japanese Crystal users. Thank you!
