### ISSUE TITLE
gitbookのi18n対応について

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/ja.crystal-lang.org#44]
crystal-jp/issues#8 で話すよりこっちで話した方がいい気がするのでissue開きます。

gitbookには標準でi18n機能があります。([ここ](http://help.gitbook.com/format/languages.html)を参照)

なのでこの機能を使っていくようにCrystalの公式に呼びかけていくのも一つの道なのかな、と思うのですけど、どうでしょうか？

**Comment by 5t111111** [comment]
自分が翻訳などをやっている別のプロジェクトですが、ここでgitbookのi18n機能を使っています。
http://voltframework.com/docs

実は私も少しこの件少し考えたことがあのですが、最初は翻訳するのがgitbookだけでなく、このリポジトリが含むもの、つまり[Crystalのページ全体](http://crystal-lang.org)を対象と考えていたので、gitbook単体でi18n機能が使えても逆にやりづらいので忘れることにしました。

今は正直翻訳するのはgitbookのドキュメントだけでいいかなあ、とか思ってます (どうせAPIリファレンスは翻訳できないし、blogの更新に毎回追いついて翻訳できる状況とも思えないし…) 。対象がgitbookだけであればそのi18n機能を使って公式に取り込むのを検討するのは大いにアリだと思います。個人的にもそれが最も望ましい姿だと思う。

自分でgitbookのi18n機能を使った限りでは、翻訳のワークフローにおいては、公式リポジトリに取り込むのも、今のように別のリポジトリにしておくのもどちらも大して変わりません。各言語のコミットが交錯するので今以上に翻訳時点の状態を意識する必要があることや、ちょっと翻訳メモリとの連携スクリプトが複雑になるくらい。

ただ、GitHub上でのやりとりや、リビルドとそのあとのデプロイなどは、今のまま自分たちの権限で自分たちの範囲のみに影響する形でやれた方が確実に楽です。
例えば日本語ドキュメントに対してPRもらったときに誰が対応するのか、とか、日本語側のみ更新したときにリビルドやデプロイを担当者に頼まないと反映されない、とかが発生します。
これはコラボレーターにしてもらってある程度自分たちでやれるようにすれば改善はしますが。

公式に管理することで上記のような問題(というか手間や考えることの増加)があることは一応経験としてお伝えします。でも、先ほどの繰り返しになりますが gitbook のみを翻訳対象とするなら、そのi18n機能を使うのが形としてはよいとは思っています。

**Comment by makenowjust** [comment]
なるほど。詳細な返事ありがとうございます。

となると、翻訳の対象をGitbookのみにするか、サイト全体にするのか意見を取った方がよさそうですね。

ボクも、現状を見る限りではGitbookだけでいいかなと思っているのですけど、みなさんどうなんでしょうか？

**Comment by pine** [comment]
初めは Gitbook のみに限っていいと思います。

あとは、トップページのみはあっていいかな (ブログと、API リファレンスを除く部分) と思います。
無駄に動いてカッコイイし。

**Comment by 5t111111** [comment]
> あとは、トップページのみはあっていいかな (ブログと、API リファレンスを除く部分) と思います。

gitbook の i18n 機能を使う場合、日本語の gitbook ドキュメントが本家サイトの docs に含まれる形になると思うので、残念ながら日本語のみのトップページを用意するのは構成的に難しそうです…

おそらく、本家サイトの docs リンクをクリックすると、言語を選択する画面を挟んで、そこで選択した言語の gitbook に遷移させる感じになると思います。
(※自動的にクライアントのロケールを見て言語を選択するようなものではなさそうです）

もし gitbook の i18n 機能を使った上でトップページを残すのであれば、Crystal-JP のトップページを作ることがあったらその時に無駄に動くあいつを取り入れるなどを検討して、そこからポータル的に直接本家サイトの日本語 gitbook にリンクするなどの形になるのかな、と思っています。

**Comment by pine** [comment]
お… てっきり暫くは gitbook の i18n を使わずに進めていく感じの流れだと思ってました。
いずれにしろ、翻訳する方がやりやすい方で進めていただけたらと、私は思います。

**Comment by 5t111111** [comment]
あ、なるほど、ちょっとテーマが2つ平行しちゃってましたね。すみません。

まずは翻訳対象が基本的に gitbook だけでいい。ということについては皆さん意見同じのようなので、
その上で gitbook の i18n 機能を使う方がよいかについては私の方でも今一度考えてみます。

**Comment by pine** [comment]
oh... 改めて issue タイトル確認したら、i18n 使うか否かの issue でした…。申し訳ない。

**Comment by pine** [comment]
そろそろ、翻訳が終わりそうなので (本当、ありがとうございます)、この件についての現時点での結論を出しておきたいなと思ってます。

i18n を使って統合する場合は、翻訳 & gitbook の知識がある @5t111111 さんに直接公式の Issue 等でやりとりしていただいたほうが、スムーズであるかなと思ってます。

一旦、Crystal-JP として公開するのであれば、公式ドメインの方に配置できるか、私の方からやりとしようと思っています。公式ドメインに CNAME 的に配置できるか? という点については、聞いてみたところ問題なさそうとの回答でした。
https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/YxvtmERLQOs

ご意見ください。

**Comment by 5t111111** [comment]
> i18n を使って統合する場合は、翻訳 & gitbook の知識がある @5t111111 さんに直接公式の Issue 等でやりとりしていただいたほうが、スムーズであるかなと思ってます。

承知しました。

gitbook の i18n 機能を使うかどうかについて考えてみました。

前に書いたように、gitbook の i18n 機能を使って公式のリポジトリ上で管理することは、自分たちで独立して管理することに比べると手間や考えることが増えてしまいます。
ぶっちゃけると、「crystal-jp としては」メリットはほぼないと思っています。

ただ、日本だけに限らない Crystal コミュニティ全体でみると、せっかく翻訳したものなので、それを他言語に先駆けて公式で公開することは価値があると思っています。というのは、上の方でも書きましたが、別のプロジェクトで、i18n 機能を使って公式に日本語訳を公開し、ドキュメントの他言語化の基盤を準備していたおかげで、別の言語 (スペイン語でした) への翻訳がプルリクエストだけでスムーズに進み、他言語圏の有志による翻訳のコントリビュートがしやすくなったということがあったためです。

これを踏まえると、当面 gitbook だけを翻訳対象と考えるのであれば、やはり自分としては手間が増えても gitbook の i18n 機能を利用する方向で進めたいと考えています。

したがって、その場合は、せっかく jp ホスト名を CNAME で公開する件に関しては問い合わせていただいたのですが、少なくとも gitbook のドキュメントに関しては公式のサブドメインを利用しない方向になります。

特に異論などがなければ、公式の issue などで提案してみます。

**Comment by pine** [comment]
i18n についてご検討ありがとうございます。i18n を使っていく方針について、承知いたしました。
お手数おかけしますが、今後ともよろしくお願いします…。

**Comment by 5t111111** [comment]
issueにあげましたー。
manastech/crystal#1673

**Comment by pine** [comment]
おおお、ありがとうございます :+1:

**Comment by 5t111111** [comment]
issueにあげたgitbookのi18n機能を使うかどうかですが、これはオリジナル側にも変更が入るため、残念ながら一朝一夕に結論が出ることはなさそうです。正直、待ってても、他言語翻訳者からも意見が出たりしないと、何ヶ月もこのまま進展がないとかも普通にありそうな感じ…

なので、もし将来的に公式でgitbookの機能をしてもそのときに移せば移行はできるし、このissueはこれとしてそのまま置いておいて、こちらでサイトを用意して公式に CNAME 貼ってもらう方向で進めちゃいましょうか？

せっかく2回目の勉強会が控えているので、そのときには正式に公開できている状態のほうが良いとも感じますし。

いかがでしょうか？

**Comment by pine** [comment]
公式のリポジトリでの議論、ありがとうございます。「最終的にはその方が望ましい形であるが、すぐに公式の gitbook に反映されるというのは難しい」という理解であっているでしょうか?

> せっかく2回目の勉強会が控えているので、そのときには正式に公開できている状態のほうが良いとも感じますし。

これは完全に同意見で、せっかく翻訳をしてくださっているので第2回の勉強会の際に、日本語版ドキュメントがあることを告知できたらな、と思っていました。

公式のドキュメントにすぐに反映することが難しいのであれば、CNAME を貼ってもらう方向で進めるのには賛成です。反対意見などがなければ、今すぐにでも進めていきたいと思います。

他の意見などある方いますでしょうか。

**Comment by 5t111111** [comment]
> 公式のリポジトリでの議論、ありがとうございます。「最終的にはその方が望ましい形であるが、すぐに公式の gitbook に反映されるというのは難しい」という理解であっているでしょうか?

いえ、議論はそこまですら進んでいません。「もし公式に翻訳を取り込むならどういう形にすればいいか」という話がまず出てきて、「そもそも公式に他言語を取り込むべきか」という話を出して、その辺で止まっちゃってる感じです。もし議論が進んだ場合、そこでgitbook自体を使うかどうかすらも白紙になる可能性までありそうです。

私個人の意見としては、前に書いた通りで、gitbookを使うのであればその機能を使って公式に取り込んだ方がよい、と思っていて、ただし、そこで発生する同期などの問題は各言語の翻訳者に任せる、でいいと思っています。が、特に同意は得られていません…

いずれにせよ、公式でこの件が優先的に検討の対象になることはなさそうなので、今すぐにでもCNAME を貼ってもらう方向で進めることに賛成です。

**Comment by pine** [comment]
> いえ、議論はそこまですら進んでいません。「もし公式に翻訳を取り込むならどういう形にすればいいか」という話がまず出てきて、「そもそも公式に他言語を取り込むべきか」という話を出して、その辺で止まっちゃってる感じです。もし議論が進んだ場合、そこでgitbook自体を使うかどうかすらも白紙になる可能性までありそうです。

oh... ちゃんと issue の方読めてませんでした。なるほど、難しい…。
英語で記述してる方や、他の言語の翻訳者などの同意を得ていかないと、厳しいのですかね…。

> いずれにせよ、公式でこの件が優先的に検討の対象になることはなさそうなので、今すぐにでもCNAME を貼ってもらう方向で進めることに賛成です。

承知しましたー。

**Comment by makenowjust** [comment]
`CNAME`を貼ってもらう、っていう方向性にはボクも賛成なのですけど、トップページやそこにあるブログの記事等々をどうするか（翻訳されていないとすごくがっかりしますし）を決めてからにしたいです

ボク自信はほとんど翻訳に関わってないし、言ってるだけなので申し訳ないのですけど‥‥。

**Comment by pine** [comment]
> トップページやそこにあるブログの記事等々をどうするか（翻訳されていないとすごくがっかりしますし）を決めてからにしたいです

ブログ記事すべて翻訳するというのは、今後も考えるととても大変であるので、
1. サイトの root をそもそも docs 以下にしてしまう
2. トップページのブログ記事を消して、トップページだけ残す

などが考えられると思います。私は 2 推しです。

**Comment by makenowjust** [comment]
> 1. サイトの root をそもそも docs 以下にしてしまう
> 2. トップページのブログ記事を消して、トップページだけ残す
> 
> などが考えられると思います。私は 2 推しです。

自分もその選択肢だったら 2 にしたいです。1 にするにはもったいないトップページだと思うので。

**Comment by 5t111111** [comment]
自分も1だとちょっと素っ気なさすぎて寂しいので、2が嬉しいです。

トップページを残す場合、APIリファレンスのリンク先とか上のファンディングのとこどうするかとか、
考えないといけないところが (ちょっとだけ) ありそうですけど、基本的には削る方向だけでいけそうですね。

**Comment by pine** [comment]
> CNAME

いまメールでお願いを送っているのですが、返信がないので GitHub の issue 立てますねー。

**Comment by pine** [comment]
自分の英語力の無さのせいか、スルーされてしまっているようなので、何かあれば突っついていただけると嬉しいです…。
https://github.com/manastech/crystal/issues/1719

**Comment by 5t111111** [comment]
一応、「こっちの事情で申し訳ないけど早く検討してほしい」との旨のコメントをしておきましたが、名指しのpingにも反応がないようなので、すぐに対応してもらうのはちょっと難しいかもしれませんね…

**Comment by pine** [comment]
ありがとうございます。

> すぐに対応してもらうのはちょっと難しいかもしれませんね…

ですかねー…。

**Comment by pine** [comment]
設定していただけました！！

https://github.com/manastech/crystal/issues/1719#issuecomment-147778587

トップページを翻訳する前提で、設定がうまく行ってるか確認したいので、一時的に設定してみます。

**Comment by pine** [comment]
ちゃんと動作しました！一旦戻しておきます。

**Comment by 5t111111** [comment]
@pine613 

よかったです！

ちなみに、

> I just added the CNAME. Note that the correct host name is ja.crystal-lang.org. Should we also set jp.crystal-lang.org?

自分もコピペしてしまって気づかなかったのですが、`jp.crystal-lang.org` が正しくて、`ja.crystal-lang.org` は不要ですよね？

`jp.crystal-lang.org` 「も」設定するか？と聞かれているので、ぴねさんの回答だとどうすればいいかわからないかもしれません。伝えておくので `jp.crystal-lang.org` 「だけ」でよくて `ja.crystal-lang.org`  はいらないのか教えてくださいー

**Comment by pine** [comment]
oh......... 全く気づかなかった…。

**Comment by pine** [comment]
地域的な意味では jp で、言語的な意味では ja かなと思い、私は ja のつもりでいましたー。

**Comment by 5t111111** [comment]
> 地域的な意味では jp で、言語的な意味では ja かなと思い、私は ja のつもりでいましたー。

なるほど。確かにこれはおっしゃる通りだと思います。

ただ、サブドメインの場合は jp の方が良く見る印象だったので、自分は先入観で jp と思っていました (今アドレスバーに jp. といれてみたら、jp.topcoder.com, jp.vuejs.com とかいくつかでてきました)。
ja は wikipedia がそうですね。

とりあえずどちらも用意してくれそうなので、`jp.crystal-lang.org` の方もよろしく、と改めてお願いしときますね。どっちかには決めないとですが、それはアンケート取ったりして決めてもいいかもですし。

**Comment by pine** [comment]
> ただ、サブドメインの場合は jp の方が良く見る印象だったので、自分は先入観で jp と思っていました (今アドレスバーに jp. といれてみたら、jp.topcoder.com, jp.vuejs.com とかいくつかでてきました)。
> ja は wikipedia がそうですね。

おー、jp も結構ありますね…。

> とりあえずどちらも用意してくれそうなので、jp.crystal-lang.org の方もよろしく、と改めてお願いしときますね。どっちかには決めないとですが、それはアンケート取ったりして決めてもいいかもですし。

よろしくおねがいしますー。

**Comment by makenowjust** [comment]
一旦closeします
