### ISSUE TITLE
翻訳担当箇所について

### ISSUE THREAD

**Issue by 5t111111** [crystal-jp/ja.crystal-lang.org#48]
@nob-suz @zchee 
翻訳のご協力ありがとうございます。コミット `fba7154` を対象とした初回の 翻訳分は、残すところ以下のセクションのみとなりました。
- 4.8
- 4.14
- 4.15
- 4.16
- 4.17

上記に関して、すでに翻訳に着手いただいているものなどございますか？
特になければ、私の方で進めていきます。念のため、あるセクションに着手する際にはその旨ここでコメントします。(gitter の方がいいかな)

もし引き続きお手伝いいただけるということであれば、同様に着手するセクションについてコメントいただければと思います。

よろしくお願いします。

**Comment by nob-suz** [comment]
着手後　遅筆ですみません　　現在サンフランシスコに出張中で、翻訳すみ箇所以外に手がついていません　かえって残っていたら、またトライします

**Comment by 5t111111** [comment]
@nob-suz
いえいえ、とても助かっています。今サンフランシスコなんですね！
もし残っていたら改めて宜しくお願いします。

**Comment by 5t111111** [comment]
これから 4.8 のセクションの翻訳に着手します。

**Comment by 5t111111** [comment]
書き忘れてましたが、4.14, 4.15翻訳中です。

**Comment by 5t111111** [comment]
- 4.16
- 4.17

も終わりました。これで一旦、コミット fba7154 を対象とした初回の翻訳分は完了しました。

**Comment by nob-suz** [comment]
素晴らしい!!　完成ですね！！　次のＷＥＢページなどの日本語化の時にチャレンジします！！

**Comment by 5t111111** [comment]
ありがとうございます！
まだ本家の最新の現在の状態の取り込みが終わっていないので、それが済めば最新の状態になります！

**Comment by pine** [comment]
本当にありがとうございます!!!!!!!

**Comment by 5t111111** [comment]
しばらくこのIssueは利用しないと思うので、とりあえずクローズします。
