### ISSUE TITLE
トップページについて

### ISSUE THREAD

**Issue by 5t111111** [crystal-jp/ja.crystal-lang.org#56]
#44 の話し合いの中で、
- トップページのブログ記事を消して、トップページだけ残す

とする方針でほぼ方針が決まっているとの認識です。

そこで、トップページを用意するにあたり、例えば以下のようなことへの決めや対応が必要と思っています。
- 翻訳する
- 日本語サイト用の文章を入れる
- ブログ記事を消す (リンクだけ消す？それとも物理的にページも消す？)
- ヘッダのファンディングを消す？
- API リファレンスへのリンクは本家のものにする

**Comment by 5t111111** [comment]
申し訳ないですが、私はトップページの対応まで手が回らなそうです。
個人的には特にトップページに対して強い要望などはないので、トップページに関することはgitbookのドキュメント翻訳とは独立して、直接上記などの対応を行っていただければと思っています。
もちろん、翻訳などで手伝いが必要であればお声がけください。ただ、トップページの翻訳ぐらいであれば翻訳メモリは不要と考えています。

**Comment by pine** [comment]
はい、必要であると思います。作業する場合は、 ブランチ切って gh-pages に反映する形でよいですか?

**Comment by 5t111111** [comment]
> はい、必要であると思います。作業する場合は、 ブランチ切って gh-pages に反映する形でよいですか?

はい、それで大丈夫です！gitbook側の更新とコンフリクトすることもないでしょうし。

**Comment by pine** [comment]
トップページ作ってみますー

**Comment by makenowjust** [comment]
おつかれさまですー

**Comment by pine** [comment]
とりあえずな翻訳と、不要そうなものの削除を行いました。
http://ja.crystal-lang.org/

**Comment by pine** [comment]
特に問題なさそうだったら、いろんなところにリンクペタペタしていこうかと思います。
あと、リビルドはやはり面倒だと感じたので、自動化しようかと…。

**Comment by 5t111111** [comment]
おお良い感じですね！
ブログがあったりと内容が多少異なるので、英語の公式 ( http://crystal-lang.org ) へのリンクがあってもいいかも？

**Comment by 5t111111** [comment]
あ、でも「コミュニティ」枠に入れるのはちょっと変か…

**Comment by pine** [comment]
内容に対しての PR とか受け付けるように、リポジトリへのリンクも欲しいかなーって思いました。

**Comment by 5t111111** [comment]
あ、確かに。それは欲しいですね。

**Comment by 5t111111** [comment]
もうトップページもできてるし、このissueは閉じて良さげなのでクローズします。

**Comment by pine** [comment]
:+1:
