### ISSUE TITLE
gh-pages ってレポジトリ名がダサい

### ISSUE THREAD

**Issue by pine** [crystal-jp/ja.crystal-lang.org#58]
docs とか official-ja ? とかにしたい。
ついでに、デフォルトブランチを master にして、gh-pages は自動でビルドかけたい。

**Comment by makenowjust** [comment]
GitHub Pagesの影響でそのサイトのドメインをレポジトリの名前にすることが多い気がするので、ja.crystal-lang.orgでいいんじゃないかと思うのですけど、どうでしょう？

**Comment by pine** [comment]
なるほど! それでよさそう (発想が貧弱だった…)。

**Comment by pine** [comment]
特に異論なければ、変更したいと思います。

**Comment by makenowjust** [comment]
異論はないです

**Comment by pine** [comment]
:+1:

**Comment by 5t111111** [comment]
私も特に異論はありません！

**Comment by pine** [comment]
:+1:

**Comment by pine** [comment]
では、ja.crystal-lang.org へ変更しますー。
git の track の設定変更等、お手数おかけします。

**Comment by pine** [comment]
変えましたー

**Comment by pine** [comment]
キャッシュの関係か、参照先が変わって not found になってるので、復活するまでおいておきます。
