### ISSUE TITLE
リビルド自動化 (Travis CI連携)

### ISSUE THREAD

**Issue by 5t111111** [crystal-jp/ja.crystal-lang.org#60]
本家と同じように Travis CI を使って

`gh-pages` への push -> リビルドして commit して push

を自動化しようと思います。
1日2日待って反対意見がなければ organization に Travis CI のアクセス権を与えてやっちゃいます。

**Comment by karupanerura** [comment]
:+1:

**Comment by pine** [comment]
:+1: やろうと思って完全に忘れてた…

**Comment by 5t111111** [comment]
もうやっちゃって良さそうなので忘れないうちにやっちゃいます！ :bow:

**Comment by pine** [comment]
ありがとうございます :+1:

**Comment by 5t111111** [comment]
#61 などで対応したのでクローズしまーす
