### ISSUE TITLE
翻訳を宣言する場所

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/ja.crystal-lang.org#86]
他の人と翻訳を箇所が被るのを避けるため、翻訳を始める前にここで宣言してください。

**Comment by arcage** [comment]
guides/performance
guides/concurrency

は昔バージョンの雑役があるのでアップデートをトライしてみます。

**Comment by at-grandpa** [comment]
crystal-book/syntax_and_semantics/is_a.md

これやってみます！

**Comment by makenowjust** [comment]
`crystal-book/syntax_and_semantics/requiring_files.md` をやっています。

**Comment by makenowjust** [comment]
「型とメソッド」の下の次のファイルを翻訳します。

- `crystal-book/syntax_and_semantics/types_and_methods.md`
- `crystal-book/syntax_and_semantics/everything_is_an_object.md`
- `crystal-book/syntax_and_semantics/the_program.md`
- `crystal-book/syntax_and_semantics/classes_and_methods.md`
- `crystal-book/syntax_and_semantics/new_initialize_and_allocate.md`
- `crystal-book/syntax_and_semantics/methods_and_instance_variables.md`
- `crystal-book/syntax_and_semantics/type_inference.md`
- `crystal-book/syntax_and_semantics/union_types.md`
- `crystal-book/syntax_and_semantics/overloading.md`
- `crystal-book/syntax_and_semantics/default_and_named_arguments.md`
- `crystal-book/syntax_and_semantics/splats_and_tuples.md`
- `crystal-book/syntax_and_semantics/type_restrictions.md`
- `crystal-book/syntax_and_semantics/return_types.md`
- `crystal-book/syntax_and_semantics/default_values_named_arguments_splats_tuples_and_overloading.md`
- `crystal-book/syntax_and_semantics/operators.md`
- `crystal-book/syntax_and_semantics/visibility.md`
- `crystal-book/syntax_and_semantics/inheritance.md`
- `crystal-book/syntax_and_semantics/virtual_and_abstract_types.md`
- `crystal-book/syntax_and_semantics/class_methods.md`
- `crystal-book/syntax_and_semantics/class_variables.md`
- `crystal-book/syntax_and_semantics/finalize.md`
- `crystal-book/syntax_and_semantics/modules.md`
- `crystal-book/syntax_and_semantics/generics.md`
- `crystal-book/syntax_and_semantics/structs.md`
- `crystal-book/syntax_and_semantics/constants.md`
- `crystal-book/syntax_and_semantics/enum.md`
- `crystal-book/syntax_and_semantics/blocks_and_procs.md`
- `crystal-book/syntax_and_semantics/capturing_blocks.md`
- `crystal-book/syntax_and_semantics/proc_literal.md`
- `crystal-book/syntax_and_semantics/block_forwarding.md`
- `crystal-book/syntax_and_semantics/closures.md`
- `crystal-book/syntax_and_semantics/alias.md`

**Comment by tobyapi** [comment]
crystal-book/syntax_and_semantics/nil_question.md

これやります！

**Comment by makenowjust** [comment]
@at-grandpa `is_a.md` の翻訳の進捗どうですか？

**Comment by arcage** [comment]
Performance次は

guides/testing

に手をつけてみようと思います。

**Comment by makenowjust** [comment]
`syntax_and_semantics/exception_handling.md` の翻訳をします。

**Comment by makenowjust** [comment]
`syntax_and_semantics/type_grammar.md` の翻訳をします。

**Comment by makenowjust** [comment]
「マクロ」以下の次の4ファイルを翻訳します。

- `crystal-book/syntax_and_semantics/macros.md`
- `crystal-book/syntax_and_semantics/macros/macro_methods.md`
- `crystal-book/syntax_and_semantics/macros/hooks.md`
- `crystal-book/syntax_and_semantics/macros/fresh_variables.md`

**Comment by makenowjust** [comment]
「アノテーション」以下の2ファイルを翻訳します。

- `crystal-book/syntax_and_semantics/annotations.md`
- `crystal-book/syntax_and_semantics/annotations/built_in_annotations.md`

**Comment by makenowjust** [comment]
`syntax_and_semantics/low_level_primitives.md` 以下を翻訳します。

**Comment by makenowjust** [comment]
`crystal-book/syntax_and_semantics/compile_time_flags.md` 以下を翻訳します。

**Comment by makenowjust** [comment]
`c_bindings` と `unsafe` の翻訳をしました。

`type_reflections` もやります。

**Comment by arcage** [comment]
conventions/配下はもう終わってましたね。

**Comment by makenowjust** [comment]
`crystal-book/guides/writing_shards.md` を翻訳をやっています。流れでそのあとの`hosting`のところもやる気がします。

**Comment by arcage** [comment]
昨日のWeeklyで話題に上がったブログポスト Towards Crystal 1.0 に手をつけてみようと思います。
